topics:
  raw_twist_cmd: "/usb_c_insertion/raw_twist_cmd"
  twist_cmd: "/twist_controller/command"
  pose_target: "/usb_c_insertion/pose_target"
  pose_servo_enable: "/usb_c_insertion/pose_servo_enable"
  wrench: "/wrench"
  script_command: "/ur_hardware_interface/script_command"
  vision_pose_debug: "/usb_c_insertion/vision_pose_debug"
