topics:
  raw_twist_cmd: "/usb_c_insertion/raw_twist_cmd"
  twist_cmd: "/twist_controller/command"
  micro_motion_active: "/usb_c_insertion/micro_motion_active"
  pose_target: "/usb_c_insertion/pose_target"
  pose_servo_enable: "/usb_c_insertion/pose_servo_enable"
  pose_servo_status: "/usb_c_insertion/pose_servo_status"
  wrench: "/wrench"
  zero_ft_service: "/ur_hardware_interface/zero_ftsensor"
  script_command: "/ur_hardware_interface/script_command"
  vision_pose_debug: "/usb_c_insertion/vision_pose_debug"
  camera_pose_debug: "/usb_c_insertion/camera_pose"
