string image_topic
string cloud_topic
float32 timeout
float32 min_blob_area
uint32 roi_radius_px
uint32 roi_stride_px
float32 depth_window_m
uint32 ransac_iterations
float32 ransac_distance_threshold
uint32 min_inliers
bool use_svd_refit
bool use_largest_component
---
bool success
string message
string error_code
geometry_msgs/PointStamped plane_point
geometry_msgs/Vector3 plane_normal
geometry_msgs/PointStamped plane_point_base
geometry_msgs/Vector3 plane_normal_base
geometry_msgs/PointStamped marker_plane_point
geometry_msgs/PointStamped marker_plane_point_base
float32 marker_center_x
float32 marker_center_y
float32 raw_center_u
float32 raw_center_v
float32 marker_area
uint32 roi_point_count
uint32 filtered_point_count
uint32 inlier_count
float32 inlier_ratio
float32 rms_error
float32 max_error
float32 elapsed
---
string stage
float32 elapsed
float32 marker_center_x
float32 marker_center_y
float32 raw_center_u
float32 raw_center_v
float32 marker_area
uint32 roi_point_count
uint32 filtered_point_count
uint32 inlier_count
float32 inlier_ratio
float32 rms_error
