string image_topic
float32 travel_distance
float32 travel_speed
float32 timeout
float32 min_blob_area
float32 min_scale_ratio
float32 max_center_shift_px
float32 max_aspect_ratio_change
float32 tool_z_direction_sign
---
bool success
string message
string error_code
geometry_msgs/PoseStamped verified_center_pose
geometry_msgs/PoseStamped final_pose
float32 traveled_distance
float32 initial_center_x
float32 initial_center_y
float32 current_center_x
float32 current_center_y
float32 initial_area
float32 current_area
float32 scale_ratio
float32 center_shift_px
float32 initial_aspect_ratio
float32 current_aspect_ratio
float32 aspect_ratio_change
float32 elapsed
---
string stage
float32 elapsed
float32 traveled_distance
float32 initial_center_x
float32 initial_center_y
float32 current_center_x
float32 current_center_y
float32 initial_area
float32 current_area
float32 scale_ratio
float32 center_shift_px
float32 aspect_ratio_change
float32 command_tool_z
